variables:
  # Set https://docs.npmjs.com/misc/config#cache - https://docs.npmjs.com/misc/config#environment-variables
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  # https://docs.cypress.io/guides/getting-started/installing-cypress.html#Binary-cache
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  paths:
    - .npm
    - cache/Cypress

test:
  image: cypress/base:10
  stage: test
  script:
    - npm ci
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - cypress/diffs/**/*.png
    reports:
      junit: cypress/results/results-*.xml
    expire_in: 2 days
