variables:
  # Set https://docs.npmjs.com/misc/config#cache - https://docs.npmjs.com/misc/config#environment-variables
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  # https://docs.cypress.io/guides/getting-started/installing-cypress.html#Binary-cache
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  paths:
    - .npm
    - cache/Cypress

test:
  only:
    refs:
      - triggers
      - web
  image: cypress/base:10
  stage: test
  script:
    - npm ci
    - $(npm bin)/cypress verify
    - |
      if [[ -v CYPRESS_baseUrl ]]; then
        echo "Testing external url $CYPRESS_baseUrl"
        npm run cy:run:ci
      else
        echo "Running local server and testing"
        npm run test:ci
      fi
  artifacts:
    when: always
    paths:
      - cypress/videos/*.mp4
      - cypress/screenshots/**/*.png
      - cypress/diffs/**/*.png
    reports:
      junit: cypress/results/results-*.xml
    expire_in: 2 days
