[build]
  command = "npm run build:netlify"
  publish = "website/public/"
  # Only trigger build if shared-types/, website/, or other core files change
  ignore = "git diff --quiet HEAD^ HEAD -- shared-types/ website/ netlify.toml tsconfig.base.json"

[build.environment]
  # Disable Cypress binary download since it takes too much time
  CYPRESS_INSTALL_BINARY = "0"

## Set up environment-specific build options

[context.production.environment]
  DISABLE_FULL_SITE = "1"
  GATSBY_USE_PROD_FIREBASE = "1"

[context.staging.environment]
  DISABLE_FULL_SITE = "1"
  GATSBY_USE_PROD_FIREBASE = "1"
