[build]
  environment = { CYPRESS_INSTALL_BINARY = "0" }

# Set up environment-specific build options
# Show guard page in production and staging environments

[context.production.environment]
  GUARD_PAGE_ONLY = "1"

[context.staging.environment]
  GUARD_PAGE_ONLY = "1"

[context.develop.environment]
  GUARD_PAGE_ONLY = "0"

[context.deploy-preview.environment]
  GUARD_PAGE_ONLY = "0"
