[build.environment]
  # Disable Cypress binary download since it takes too much time
  CYPRESS_INSTALL_BINARY = "0"

## Set up environment-specific build options

[context.production.environment]
  # Disable anything other than save the date page
  ENABLE_FULL_SITE = "0"
  # Use production Firebase config
  GATSBY_USE_PROD_FIREBASE = "1"

[context.staging.environment]
  # Disable anything other than save the date page
  ENABLE_FULL_SITE = "0"
  # Use production Firebase config
  GATSBY_USE_PROD_FIREBASE = "1"

[context.develop]
  # Run production tests in develop environment
  command = "npm run build && ./trigger-github.sh"
[context.develop.environment]
  ENABLE_FULL_SITE = "1"
  GATSBY_USE_PROD_FIREBASE = "0"

[context.deploy-preview.environment]
  ENABLE_FULL_SITE = "1"
  GATSBY_USE_PROD_FIREBASE = "0"
