[build.environment]
  # Disable Cypress binary download since it takes too much time
  CYPRESS_INSTALL_BINARY = "0"

## Set up environment-specific build options

[context.production.environment]
  # Disable anything other than guard page in production environment
  ENABLE_FULL_SITE = "0"

[context.staging]
  # Run production tests in staging environment
  command = "npm run build && ./trigger-gitlab.sh"
[context.staging.environment]
  # Disable anything other than guard page in staging environment
  ENABLE_FULL_SITE = "0"

[context.develop.environment]
  ENABLE_FULL_SITE = "1"

[context.deploy-preview.environment]
  ENABLE_FULL_SITE = "1"
