[build]
  command = "npm run build"
  publish = "public/"
  base = "website/"
  # The functions/ directory does not actually contain Netlify functions
  functions = "nofunctions/"

[build.environment]
  # Disable Cypress binary download since it takes too much time
  CYPRESS_INSTALL_BINARY = "0"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

## Set up environment-specific build options

# Trigger deploy publish via GitHub (after tests)
[context.production]
  command = "npm run build && ./trigger-github.sh"

[context.production.environment]
  DISABLE_DEMO_PAGES = "1"
  GATSBY_DISABLE_FULL_SITE = "1"
  GATSBY_USE_PROD_FIREBASE = "1"
  GATSBY_GA_BRANCH = "master"

[context.deploy-preview.environment]
  GATSBY_GA_BRANCH = "develop"
