version: 1
snapshot:
  widths: [375, 1280]
  percy-css: |
    .p-cover::after {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      background-color: white;
      text-color: white;
      content: " ";
    }

    .p-hide {
      display: none;
    }
