version: 1
snapshot:
  widths: [375, 768, 1280]
  percy-css: |
    .full-screen-hero::after, .hero::after {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      background-color: white;
      content: " ";
    }
