name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install and test
      run: |
        npm ci
        $(npm bin)/cypress verify
        npm run test:ci
      env:
        CI: true
