name: Build and test
on:
  push:
    branches:
      # Match all branches except staging and master (since we test it before develop anyway)
      - '*'
      - '!staging'
      - '!master'
    paths:
      - '*'
      - '!README.md'
      - '!LICENSE'
      - '!.prettierrc'
      - '!.prettierignore'
      - '!.gitignore'
      - '!.vscode/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
        $(npm bin)/cypress verify
      env:
        CI: true
    - name: Run tests
      run: |
        npm run test:ci
      env:
        CI: true
