name: Build and test
on:
  push:
    branches-ignore:
      - 'staging'
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
        $(npm bin)/cypress verify
      env:
        CI: true
    - name: Run tests
      run: |
        npm run test:ci
      env:
        # Enable full site tests for all tests during development
        ENABLE_FULL_SITE: 1
        CYPRESS_ENABLE_FULL_SITE: 1
        CI: true
        # Provide firebase credentials to app for integration tests
        GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
        GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
        GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    - name: Archive Cypress videos
      uses: actions/upload-artifact@v1
      with:
        name: videos
        path: cypress/videos
