name: CLI tests
on:
  push:
    paths:
      - 'cli/**'
      - '.github/workflows/cli-tests.yml'
jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
      working-directory: ./cli
    - name: Run tests
      run: |
        npm run test:ci
      working-directory: ./cli
      env:
        CI: true
