name: External test
on: repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
      with:
        # Always build and run external tests on 'develop' branch
        ref: develop
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
        $(npm bin)/cypress verify
      working-directory: ./website
      env:
        CI: true
    - name: Run tests for external URL
      if: startsWith(github.event.action, 'externalUrl_')
      env:
        PERCY_ENABLE: 0
        CI: true
        ACTION: ${{ github.event.action }}
      run: |
        export CYPRESS_baseUrl="${ACTION#externalUrl_}"
        echo "Running tests with external URL ${CYPRESS_baseUrl}..."
        npm run cy:run:ci
      working-directory: ./website
    - name: Archive Cypress videos
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: videos
        path: website/cypress/videos
