name: Firebase staging deploy
on:
  push:
    branches:
      - 'develop'
      - 'staging'
    paths:
      - 'functions/**'
      - 'firestore.rules'
      - '.github/workflows/firebase-deploy.yml'
jobs:
  deploy:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
      working-directory: ./functions
    - name: Run tests
      run: |
        npm run test:ci
      working-directory: ./functions
      env:
        CI: true
    - name: Deploy (staging)
      run: |
        npm run deploy
      working-directory: ./functions
      if: github.ref == "refs/heads/develop"
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Deploy (prod)
      run: |
        npm run deploy:prod
      working-directory: ./functions
      if: github.ref == "refs/heads/staging"
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
