name: Firebase tests and deploy
on:
  push:
    paths:
      - "functions/**"
      - "firestore.rules"
      - ".github/workflows/firebase-deploy.yml"
jobs:
  deploy:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install packages
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./functions
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{
            hashFiles('~/.cache/firebase/emulators/**') }}
      - name: Run tests
        run: |
          npm run test:ci
        working-directory: ./functions
        env:
          CI: true
      - name: Deploy and seed data (staging project)
        run: |
          npm run deploy
          curl -X POST -d {} https://test-alisha-and-milind-wedding.firebaseapp.com/seedInvitations
        working-directory: ./functions
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy (production project)
        if: github.ref == 'refs/heads/master'
        run: |
          npm run deploy:prod
        working-directory: ./functions
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
