name: Website tests
on:
  push:
    branches-ignore:
      - 'staging'
      - 'master'
    paths:
      - 'website/**'
      - '.github/workflows/website-tests.yml'
      - 'package.json'
      - 'package-lock.json'
  repository_dispatch: {}
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      if: github.event_name != 'repository_dispatch'
      uses: actions/checkout@v1
    - name: Check out repository (external dispatch)
      if: github.event_name == 'repository_dispatch'
      uses: actions/checkout@v1
      with:
        # Always build and run external dispatch tests on 'develop' branch
        ref: develop
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        npm ci
        $(npm bin)/cypress verify
      working-directory: ./website
      env:
        CI: true
    - name: Run tests
      if: github.event_name == 'push'
      run: |
        export PERCY_BRANCH="${GITHUB_REF#refs/heads/}"
        export PERCY_COMMIT="$GITHUB_SHA"
        if [[ "$PERCY_BRANCH" = renovate* ]]; then
          echo "Disabling Percy for renovate branch"
          export PERCY_ENABLE=0
        fi
        npm run test:ci
      working-directory: ./website
      env:
        CI: true
        GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
        GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
        GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        CYPRESS_SEED_URL: ${{ secrets.SEED_URL }}
        IS_RENOVATE_BRANCH: ${{ github.ref }}
    - name: Run tests (external dispatch)
      if: startsWith(github.event.action, 'externalUrl_')
      env:
        PERCY_ENABLE: 0
        CI: true
        ACTION: ${{ github.event.action }}
      run: |
        export CYPRESS_baseUrl="${ACTION#externalUrl_}"
        echo "Running tests with external URL ${CYPRESS_baseUrl}..."
        npm run cy:run:ci
      working-directory: ./website
    - name: Archive Cypress videos
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: videos
        path: website/cypress/videos
